{
 "title": "Janus",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "DataSource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Request count by path",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_proxy_request_count_by_path{job=\"bytehouse-enterprise-janus\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request latency (ms) by path P95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_proxy_request_latency_by_path_bucket{job=\"bytehouse-enterprise-janus\"}[$__rate_interval])) by (upstream_path,le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failure requests rate per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(http_server_response_count_by_path_code_and_method{job=\"bytehouse-enterprise-janus\",http_status=~\"[45].*\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request size (bytes) P95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_request_size_bucket{job=\"bytehouse-enterprise-janus\"}[$__rate_interval])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}